FROM ruby:2.4.4 AS build

RUN curl -o /usr/local/share/ca-certificates/MITRE_BA_Root.crt http://pki.mitre.org/MITRE%20BA%20Root.crt
RUN curl -o /usr/local/share/ca-certificates/MITRE_BA_NPE_CA-1.crt http://pki.mitre.org/MITRE%20BA%20NPE%20CA-1.crt
RUN curl -o /usr/local/share/ca-certificates/MITRE_BA_NPE_CA-3.crt http://pki.mitre.org/MITRE%20BA%20NPE%20CA-3.crt
RUN update-ca-certificates
RUN echo "Acquire::http::Proxy \"http://gatekeeper.mitre.org:80\";" >> /etc/apt/apt.conf

RUN apt-get update && apt-get install -y build-essential libpq-dev nodejs

# Deploy production server to container
ARG RAILS_ENV=production
ARG RAILS_RELATIVE_URL_ROOT=/heimdall

ARG RAILS_ROOT=/var/www/heimdall

RUN mkdir -p $RAILS_ROOT/tmp/pids

WORKDIR $RAILS_ROOT

COPY Gemfile* $RAILS_ROOT

RUN gem install bundler && bundle install --jobs 20 --retry 5 --path vendor/bundle/
ENV http_proxy=""
ENV https_proxy=""
ENV no_proxy="127.0.0.1,localhost,.mitre.org"

COPY . $RAILS_ROOT

RUN mv config/mongoid.yml config/mongoid.yml.orig
RUN mv config/mongoid.yml.docker config/mongoid.yml
RUN echo $http_proxy

# precompile is only necessary for production builds
RUN cp config/secrets.example.yml config/secrets.yml
# swarm secrets are not available until run
RUN bash -c "RAILS_ENV=$RAILS_ENV RAILS_RELATIVE_URL_ROOT=$RAILS_RELATIVE_URL_ROOT SECRET_KEY_BASE=$(openssl rand -hex 64) bundle exec rake assets:precompile"
RUN rm config/secrets.yml
# Generate a symlink into a named volume or use docker secrets, DOCKER_SECRETS
# assumes the secret is mounted explicitly at run time.
# RUN bash -c "[[ -n \"$DOCKER_SECRETS\" ]] || { mkdir -p /srv/secrets/ && touch /srv/secrets/secrets.yml && ln -s /srv/secrets/secrets.yml config/secrets.yml  && rm -rfv /srv/secrets ; }"
RUN useradd -r -u 80 www
RUN chown -R www /var/www/heimdall 
EXPOSE 3000

ENTRYPOINT ["bundle", "exec"]

USER www
CMD ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
